split definitions about gflog_reduced_*() from gfutil.h to gflog_reduced.h, to avoid the following warning in multiple files on Linux: gfutil.h:36: error: expected specifier-qualifier-list before 'time_t'
this warning was introduced in r6951 as follows:
move the reduced log function to libgfarm as a preparation to fix #504 - gfsd stops to work with a message "<err> ![1000551] cannot set canonical hostname of this node", when gfmd is overloaded


git-svn-id: svn://svn.code.sf.net/p/gfarm/code/gfarm_v2/trunk@6962 4a5e1ece-6a47-475c-b646-731d720b41d0