merge r8959 from the 2.6 branch:
fix the following error on Solaris, by defining _POSIX_PTHREAD_SEMANTICS:
	gfprep.c:2955: too many arguments to function `sigwait'

this problem was introduced in r8393 (for #709)
to support SIGTERM/SIGINT/SIGHUP to remove replicas certainly


git-svn-id: svn://svn.code.sf.net/p/gfarm/code/gfarm_v2/branches/2.5@8961 4a5e1ece-6a47-475c-b646-731d720b41d0